name: CORE_CD

# on:
#  push:
#    branches:
      # uncomment line below to run actions after push to master branch
      # - master 

jobs:
  build:

    runs-on: self-hosted

    env:
      Solution_Path: Core.sln
      build_script: build.ps1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name:  Build and Pack app then copy packages and libs to specific directories
      run: .\build.ps1 -Pack

